### ISSUE TITLE
The resulting data is divided into several segments

### ISSUE THREAD

**Issue by 7571deng** [FengChendian/serial_port_win32#29]
![企业微信截图_321852b0-68b3-4ad8-a949-a998f0fb17c1](https://github.com/FengChendian/serial_port_win32/assets/19684678/7ac9e7ba-fe76-4bea-bd21-bdef3a2f83ad)

**Comment by FengChendian** [comment]
No `\0` in your string. It's possible to truncate your string due to windows API. And the API is designed that Windows will return the read data when it returns the sending is complete (Maybe I/O just delay).

You can increase `dataPollingInterval` to wait data io is complete. Or use `readBytesUntil` function.

```dart
  void readBytesOnListen(int bytesSize, Function(Uint8List value) onData,
      {void onBefore()?,
      Duration dataPollingInterval = const Duration(microseconds: 500)})
```

**Comment by FengChendian** [comment]
In version 2.0.1, there are 3 different APIs to read data. And `readOnListen` is removed because lack of flexible timeout control.
You can use `readBytesUntil` or `readBytes` with timeout or `readFixedSizeBytes` to read sized data which you want

```dart
print(await port.readBytesUntil(Uint8List.fromList("T".codeUnits))); /// '\0' is not included
/// or
var read = port.readBytes(18, timeout: Duration(milliseconds: 10))..then((onValue) => print(onValue));
var result = await read;
print(result);
/// or
var fixedBytesRead = port.readFixedSizeBytes(2)..then((onValue) => print(onValue));
await fixedBytesRead;
```
