### ISSUE TITLE
How to check if COM port is disconnected

### ISSUE THREAD

**Issue by sneiksus** [FengChendian/serial_port_win32#33]
Greeting, is there a way to check that USB cable was unpluged? _isOpened_ property always return true even when the usb cable was physically disconnected?

**Comment by FengChendian** [comment]
`isOpened ` property just reflects user code states in dart. So it's true if the usb cable was physically disconnected.

I know you want `isOpened` to automatically become false when cable disconnected. It needs **WNDPROC callback function** in winuser.h

I didn't implement this function because I don't know how dart implements win32 system callback function. 😭 Maybe win32 package supports this function now. I will try it.

Now, there are some other solutions to check USB COM PORT connection status:

1. Using `getAvailablePorts` function to compare lists
2. try write bytes or read bytes, and catch exception
3. try close and reopen it
